"""
Pydantic schemas for request/response validation.
"""

from pathlib import Path
from pydantic import BaseModel, Field
from typing import Optional, Dict, List


class ShotRequest(BaseModel):
    """
    Request schema for xG prediction.
    """

    x: float = Field(
        ..., description="X-coordinate of shot (0-120, goal at 120)", ge=0, le=120
    )
    y: float = Field(
        ..., description="Y-coordinate of shot (0-80, center at 40)", ge=0, le=80
    )
    body_part: str = Field(
        default="Right Foot",
        description="Body part used for the shot",
        pattern="^(Right Foot|Left Foot|Head|Other)$",
    )
    is_open_play: bool = Field(
        default=True, description="Whether the shot was from open play"
    )
    one_on_one: bool = Field(
        default=False, description="Whether the shot was a one-on-one situation"
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "x": 108.0,
                    "y": 40.0,
                    "description": "Penalty spot - central position",
                },
                {"x": 102.0, "y": 40.0, "description": "Edge of box - central"},
                {"x": 108.0, "y": 10.0, "description": "Wing position - tight angle"},
            ]
        }
    }


# TODO Expanded response with shot details
class ShotResponse(BaseModel):
    """
    Response schema for xG prediction.
    """

    xG: float = Field(..., description="Expected goals probability (0-1)", ge=0, le=1)
    shot_distance: float = Field(
        ..., description="Distance from shot location to goal (yards)"
    )
    shot_angle: float = Field(..., description="Shooting angle (degrees)")
    quality: str = Field(..., description="Shot quality interpretation")

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "xG": 0.2456,
                    "shot_distance": 12.0,
                    "shot_angle": 18.43,
                    "quality": "Good",
                }
            ]
        }
    }


class XGModelTrainRequest(BaseModel):
    """
    Request schema for training a new xG model.
    """

    features_path: Optional[Path] = Field(
        None,
        description="Path to features file (default: data/gold/xg_features.parquet)",
    )
    output_path: Optional[Path] = Field(
        None,
        description="Path to save the trained model (default: models/xg_model.pkl)",
    )
    test_size: float = Field(
        0.2,
        description="Proportion of data to use for testing (default: 0.2)",
        ge=0.0,
        le=1.0,
    )
    random_state: int = Field(
        42, description="Random state for reproducibility (default: 42)"
    )
    max_iter: int = Field(
        1000, description="Maximum iterations for the solver (default: 1000)", ge=100
    )
    run_name: Optional[str] = Field(
        None, description="Name for the MLflow run (default: autogenerated)"
    )
    experiment_name: str = Field(
        "Default", description="Name of the MLflow experiment (default: Default)"
    )
    model_name: str = Field(
        "xG Model", description="Name of the model (default: xG Model)"
    )


class HealthResponse(BaseModel):
    """Health check response."""

    status: str = Field(..., description="Service status")
    model_loaded: bool = Field(..., description="Whether xG model is loaded")
    version: str = Field(default="1.0.0", description="API version")


class ErrorResponse(BaseModel):
    """Error response schema."""

    error: str = Field(..., description="Error message")
    detail: Optional[str] = Field(None, description="Detailed error information")


class XGModelMetadata(BaseModel):
    """Metadata about a single xG model version."""

    model_id: str = Field(..., description="Convenient identifier (name@version)")
    model_key: str = Field(..., description="Alias key (matches model_id)")
    name: str = Field(..., description="Registered model name")
    display_name: str = Field(..., description="Human-friendly name with version")
    version: int = Field(..., description="MLflow model version number", ge=1)
    stage: Optional[str] = Field(None, description="MLflow stage (e.g. Production)")
    run_id: str = Field(..., description="MLflow run ID")
    created_at: int = Field(..., description="Creation timestamp (ms since epoch)")
    metrics: Dict[str, float] = Field(
        default_factory=dict, description="Evaluation metrics logged during training"
    )
    tags: Dict[str, str] = Field(
        default_factory=dict, description="MLflow tags associated with the run"
    )


class XGModelListResponse(BaseModel):
    """Response for GET /models."""

    models: List[XGModelMetadata] = Field(..., description="Discovered model versions")
    current_model: Optional[str] = Field(
        None, description="Currently selected model identifier"
    )
    count: int = Field(..., description="Number of models returned", ge=0)


class SelectModelResponse(BaseModel):
    """Response for POST /models/select."""

    status: str = Field(..., description="Operation status")
    selected_model: Optional[XGModelMetadata] = Field(
        None, description="Metadata for the activated model"
    )
    message: str = Field(..., description="Human-readable status message")


class ModelFeatureSet(BaseModel):
    """Represents the ordered feature vector for a specific model."""

    model_id: str = Field(..., description="Model identifier (name@version)")
    display_name: Optional[str] = Field(
        None, description="Human-readable name for the model"
    )
    stage: Optional[str] = Field(None, description="MLflow stage")
    run_id: Optional[str] = Field(None, description="MLflow run identifier")
    feature_count: int = Field(..., description="Length of the feature vector", ge=0)
    features: List[str] = Field(..., description="Ordered feature names")
    body_part_options: List[str] = Field(
        default_factory=list,
        description="Body part categories inferred from one-hot columns",
    )


class ModelFeatureError(BaseModel):
    """Represents a model that failed to load when building feature metadata."""

    model_id: str = Field(..., description="Model identifier that failed to load")
    error: str = Field(..., description="Error message")


class ModelFeatureListResponse(BaseModel):
    """Response for GET /models/features."""

    models: List[ModelFeatureSet] = Field(..., description="Feature metadata per model")
    count: int = Field(..., description="Number of models with feature metadata", ge=0)
    errors: Optional[List[ModelFeatureError]] = Field(
        None, description="Optional list of registry entries that failed to load"
    )
